//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsStore.Domain.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wallpaper
    {
        public int WallpaperId { get; set; }
        public string WallpaperImg { get; set; }
        public string LinkPage { get; set; }
        public string WallpaperName { get; set; }
        public Nullable<bool> Display { get; set; }
    }
}
